/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package drawingprogram;

import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;

/**
 * This is a JFrame form that displays a file save dialog box so the user
 * can select a filename and location to save the image as a png file
 * @author clatulip
 */
public class SaveDialogWindow extends javax.swing.JFrame {

    private DrawingCanvas myCanvas;
    /**
     * Creates new form SaveDialogWindow
     */
    public SaveDialogWindow(DrawingCanvas canvas) {
        // need access to the canvas to get the image
        myCanvas = canvas;
        // sets up the fileChooser stuff
        initComponents();
        // make this window just disappear when user clicks close
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SaveDialog = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SaveDialog.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        SaveDialog.setApproveButtonText("");
        SaveDialog.setSelectedFile(new java.io.File("/myPicture.png"));
        SaveDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SaveDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SaveDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This handler gets called when the user clicks either Save or Cancel.
     * It checks to see if user selected a filename & location
     * If so, we get the picture from canvas and save it out as png
     * @param evt 
     */
    private void SaveDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveDialogActionPerformed
        // try to get the file (this will be null if user hit cancel)
        File saveFile = SaveDialog.getSelectedFile();
        // see if we actually got a file name and location
        if (saveFile != null) {
            // get image from canvas
            BufferedImage image = new BufferedImage(myCanvas.getWidth(), myCanvas.getHeight(), BufferedImage.TYPE_INT_RGB);
            
            // create a graphics2D object out of the image
            Graphics2D graphics2D = image.createGraphics(); 
            myCanvas.paint(graphics2D);
            
            // try to save image out to the png
            try{
                ImageIO.write(image,"png", saveFile);
            }
             catch(Exception ex){
                 System.out.println("Problem saving out png file.");
             }
        }
        
        // now we are done, so get rid of this window
        this.dispose();

    }//GEN-LAST:event_SaveDialogActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser SaveDialog;
    // End of variables declaration//GEN-END:variables
}
